# Generated by Django 3.1.4 on 2020-12-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
