# Generated by Django 3.1.4 on 2020-12-02 13:33

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lexer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="Paste",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(default="")),
                (
                    "inspiration_date",
                    models.DateField(
                        default=datetime.datetime(2020, 12, 9, 13, 33, 47, 290810)
                    ),
                ),
                (
                    "lex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paste.lexer"
                    ),
                ),
            ],
        ),
    ]
