# Generated by Django 3.1.4 on 2020-12-07 12:24

import datetime
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="uuid",
            field=models.CharField(
                default=uuid.UUID("26231afe-3887-11eb-820b-a8a15909c179"),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paste",
            name="inspiration_date",
            field=models.DateField(
                default=datetime.datetime(2020, 12, 14, 12, 24, 27, 651133)
            ),
        ),
    ]
