# Generated by Django 3.1.4 on 2020-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0002_auto_20201207_1224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paste",
            name="inspiration_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="paste",
            name="uuid",
            field=models.CharField(max_length=255),
        ),
    ]
