# Generated by Django 3.1.4 on 2020-12-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0003_auto_20201208_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="name",
            field=models.CharField(default="Text snippet", max_length=255),
        ),
    ]
