name: Backend-CI-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          cd share
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: CI process
        run: |
          cd backend
          inv check
          inv test
